// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtNRSc0V3LQBw6LYWrNDMNoU_2FQ4zpUM',
    appId: '1:35933528017:web:e035d1da814f5e35be0af0',
    messagingSenderId: '35933528017',
    projectId: 'messageme-app-39008',
    authDomain: 'messageme-app-39008.firebaseapp.com',
    storageBucket: 'messageme-app-39008.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6dQqm51QqLTiyEpdWTvWH1CrIRbO-6mo',
    appId: '1:35933528017:android:928d1508b044c634be0af0',
    messagingSenderId: '35933528017',
    projectId: 'messageme-app-39008',
    storageBucket: 'messageme-app-39008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nIiS1iS7N8Wrztt_mKMw1c4kTzhQl2I',
    appId: '1:35933528017:ios:c795aa05ed3fd7c2be0af0',
    messagingSenderId: '35933528017',
    projectId: 'messageme-app-39008',
    storageBucket: 'messageme-app-39008.appspot.com',
    iosClientId: '35933528017-1at8g32dcq0pgblm1ksqdp740n8p3qso.apps.googleusercontent.com',
    iosBundleId: 'com.example.firTst',
  );
}
